### ISSUE TITLE
Issue with processing multiple .nessus files that are in different folders.

### ISSUE THREAD

**Issue by JTGM0131** [cheeyuenteng/automate_the_world#1]
The vapt_raw_to_xlsx.py are not able to process the .nessus properly when it is inserted as a directory. It is caused by the script only process the variable "filename" rather than the full file path. Not sure how many scripts are affected but I have suggested some edit in the code in below:

`if os.path.isdir(args.f):
		output = list()
		for filename in os.listdir(args.f):
			if filename.endswith('.nessus'):
				output += main(str(args.f)+filename)
				output = remove_duplicate(output)
`

![index](https://user-images.githubusercontent.com/5830788/70030398-1b1f8a00-15e4-11ea-8190-5eebf9e01b7b.jpg)

**Comment by cheeyuenteng** [comment]
This bug has been fixed and push to the master branch. Please pull the repo again for the updates. Thank you.
